// import { Caveat } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/layouts/Navbar";
// import Footer from "@/components/layouts/Footer";

// const caveat = Caveat({
//   variable: "--font-caveat",
//   subsets: ["latin"],
//   display: "swap",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html className="bg-white " lang="en">
//       <body
//         className={`${caveat.className} antialiased overflow-x-hidden`}
//       >
//         <Navbar />
//         <div className="max-w-screen-3xl mx-auto">
//           {children}
//         </div>
//         <div className="bg-[#F7F8ED]">
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }

"use client";

import React, { useEffect, useRef } from "react";

export default function CarRacingGame() {
  const gameRef = useRef(null);

  useEffect(() => {
    // --- GAME LOGIC ---
    const canvas = document.getElementById("road-canvas");
    const ctx = canvas.getContext("2d");
    const overlay = document.getElementById("overlay");
    const startBtn = document.getElementById("start-btn");
    const scoreHud = document.getElementById("score-hud");
    const speedHud = document.getElementById("speed-hud");
    const bestHud = document.getElementById("best-hud");
    const overlayScore = document.getElementById("overlay-score");
    const btnLeft = document.getElementById("btn-left");
    const btnRight = document.getElementById("btn-right");

    const W = 400,
      H = 480;
    canvas.width = W;
    canvas.height = H;
    canvas.style.width = "100%";
    canvas.style.height = "auto";

    let state = "idle";
    let score = 0,
      best = 0,
      speed = 3;
    let playerX = W / 2;
    let playerY = H - 100;
    const playerW = 36,
      playerH = 60;
    let leftKey = false,
      rightKey = false;
    let enemies = [];
    let roadLines = [];
    let particles = [];
    let frame = 0;
    let animId;

    const LANE_CENTERS = [W * 0.2, W * 0.4, W * 0.6, W * 0.8];
    const ROAD_LEFT = W * 0.08,
      ROAD_RIGHT = W * 0.92;

    function initRoad() {
      roadLines = [];
      for (let i = 0; i < 8; i++) roadLines.push({ y: i * 70 });
    }

    function spawnEnemy() {
      const lane = LANE_CENTERS[Math.floor(Math.random() * LANE_CENTERS.length)];
      const colors = ["#ff4455", "#ff8c00", "#aa44ff", "#00ccff", "#44ff88"];
      enemies.push({
        x: lane,
        y: -70,
        w: 34,
        h: 58,
        color: colors[Math.floor(Math.random() * colors.length)],
        lane,
      });
    }

    function drawRoad() {
      ctx.fillStyle = "#111118";
      ctx.fillRect(0, 0, W, H);
      ctx.fillStyle = "#0e0e18";
      ctx.fillRect(ROAD_LEFT, 0, ROAD_RIGHT - ROAD_LEFT, H);
      ctx.strokeStyle = "#1a1a30";
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(ROAD_LEFT, 0);
      ctx.lineTo(ROAD_LEFT, H);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(ROAD_RIGHT, 0);
      ctx.lineTo(ROAD_RIGHT, H);
      ctx.stroke();
      ctx.strokeStyle = "#2a2a50";
      ctx.lineWidth = 1;
      ctx.setLineDash([30, 40]);
      for (let lx of [W * 0.33, W * 0.5, W * 0.67]) {
        ctx.beginPath();
        ctx.moveTo(lx, 0);
        ctx.lineTo(lx, H);
        ctx.stroke();
      }
      ctx.setLineDash([]);
    }

    function drawRoadLines() {
      ctx.fillStyle = "#ffffff18";
      for (let l of roadLines) {
        ctx.fillRect(W * 0.49, l.y, 4, 28);
      }
    }

    function drawCar(x, y, w, h, color, isPlayer) {
      const cx = x - w / 2,
        cy = y - h / 2;
      ctx.save();
      if (isPlayer) {
        ctx.shadowColor = "#00f0ff";
        ctx.shadowBlur = 16;
      }
      ctx.fillStyle = color;
      ctx.beginPath();
      ctx.roundRect(cx, cy + h * 0.15, w, h * 0.7, 4);
      ctx.fill();
      ctx.fillStyle = isPlayer ? "#003344" : "#330011";
      ctx.beginPath();
      ctx.roundRect(cx + w * 0.1, cy + h * 0.28, w * 0.8, h * 0.3, 3);
      ctx.fill();
      ctx.fillStyle = isPlayer ? "#00f0ff44" : "#ffffff22";
      ctx.fillRect(cx + w * 0.12, cy + h * 0.3, w * 0.76, h * 0.25);
      ctx.fillStyle = "#111";
      ctx.beginPath();
      ctx.ellipse(cx + w * 0.18, cy + h * 0.12, w * 0.14, h * 0.08, 0, 0, Math.PI * 2);
      ctx.fill();
      ctx.beginPath();
      ctx.ellipse(cx + w - w * 0.18, cy + h * 0.12, w * 0.14, h * 0.08, 0, 0, Math.PI * 2);
      ctx.fill();
      ctx.beginPath();
      ctx.ellipse(cx + w * 0.18, cy + h * 0.88, w * 0.14, h * 0.08, 0, 0, Math.PI * 2);
      ctx.fill();
      ctx.beginPath();
      ctx.ellipse(cx + w - w * 0.18, cy + h * 0.88, w * 0.14, h * 0.08, 0, 0, Math.PI * 2);
      ctx.fill();
      if (isPlayer) {
        ctx.fillStyle = "#00f0ffcc";
        ctx.beginPath();
        ctx.ellipse(cx + w * 0.25, cy + h * 0.95, w * 0.09, h * 0.04, 0, 0, Math.PI * 2);
        ctx.fill();
        ctx.beginPath();
        ctx.ellipse(cx + w * 0.75, cy + h * 0.95, w * 0.09, h * 0.04, 0, 0, Math.PI * 2);
        ctx.fill();
      }
      ctx.restore();
    }

    function drawParticles() {
      for (let p of particles) {
        ctx.globalAlpha = p.life / p.maxLife;
        ctx.fillStyle = p.color;
        ctx.beginPath();
        ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
        ctx.fill();
      }
      ctx.globalAlpha = 1;
    }

    function spawnExplosion(x, y) {
      for (let i = 0; i < 24; i++) {
        const ang = Math.random() * Math.PI * 2;
        const sp = 1 + Math.random() * 5;
        particles.push({
          x,
          y,
          vx: Math.cos(ang) * sp,
          vy: Math.sin(ang) * sp,
          r: 2 + Math.random() * 4,
          color: ["#ff4455", "#ff8c00", "#ffd700", "#fff"][Math.floor(Math.random() * 4)],
          life: 30,
          maxLife: 30,
        });
      }
    }

    function spawnTrail() {
      particles.push({
        x: playerX - 6 + Math.random() * 12,
        y: playerY + playerH / 2 - 10,
        vx: (Math.random() - 0.5) * 0.5,
        vy: speed * 0.3 + Math.random(),
        r: 3 + Math.random() * 3,
        color: "#00f0ff",
        life: 18,
        maxLife: 18,
      });
    }

    function checkCollision(a, b) {
      return (
        Math.abs(a.x - b.x) < (playerW + b.w) * 0.42 &&
        Math.abs(a.y - b.y) < (playerH + b.h) * 0.42
      );
    }

    function gameLoop() {
      frame++;
      if (leftKey && playerX > ROAD_LEFT + playerW / 2 + 4) playerX -= speed * 0.8;
      if (rightKey && playerX < ROAD_RIGHT - playerW / 2 - 4) playerX += speed * 0.8;

      speed = 3 + Math.floor(score / 300) * 0.5;
      if (speed > 14) speed = 14;

      for (let l of roadLines) {
        l.y += speed;
        if (l.y > H) l.y -= 560;
      }

      if (frame % Math.max(40 - Math.floor(score / 200), 18) === 0) spawnEnemy();

      for (let e of enemies) e.y += speed * 1.1;
      enemies = enemies.filter((e) => e.y < H + 80);

      for (let e of enemies) {
        if (checkCollision({ x: playerX, y: playerY }, e)) {
          spawnExplosion(playerX, playerY);
          endGame();
          return;
        }
      }

      if (frame % 2 === 0) spawnTrail();

      for (let p of particles) {
        p.x += p.vx;
        p.y += p.vy;
        p.life--;
      }
      particles = particles.filter((p) => p.life > 0);

      score += Math.round(speed * 0.4);
      scoreHud.textContent = score;
      speedHud.textContent = Math.round(speed * 28);

      drawRoad();
      drawRoadLines();
      drawParticles();
      for (let e of enemies) drawCar(e.x, e.y, e.w, e.h, e.color, false);
      drawCar(playerX, playerY, playerW, playerH, "#00f0ff", true);

      animId = requestAnimationFrame(gameLoop);
    }

    function startGame() {
      score = 0;
      speed = 3;
      frame = 0;
      playerX = W / 2;
      playerY = H - 100;
      enemies = [];
      particles = [];
      initRoad();
      overlay.style.display = "none";
      state = "playing";
      gameLoop();
    }

    function endGame() {
      cancelAnimationFrame(animId);
      state = "over";
      if (score > best) best = score;
      bestHud.textContent = best;
      overlayScore.textContent = "SCORE: " + score + (score >= best ? " ★ NEW BEST" : "");
      overlayScore.style.display = "block";
      overlay.querySelector("h1").textContent = "GAME OVER";
      startBtn.textContent = "TRY AGAIN";
      overlay.style.display = "flex";
    }

    // --- EVENT LISTENERS ---
    const handleKeyDown = (e) => {
      if (e.key === "ArrowLeft") {
        leftKey = true;
        btnLeft.classList.add("pressed");
      }
      if (e.key === "ArrowRight") {
        rightKey = true;
        btnRight.classList.add("pressed");
      }
      if ((e.key === "Enter" || e.key === " ") && state !== "playing") startGame();
      if (["ArrowLeft", "ArrowRight", " "].includes(e.key)) e.preventDefault();
    };

    const handleKeyUp = (e) => {
      if (e.key === "ArrowLeft") {
        leftKey = false;
        btnLeft.classList.remove("pressed");
      }
      if (e.key === "ArrowRight") {
        rightKey = false;
        btnRight.classList.remove("pressed");
      }
    };

    const handleLeftDown = () => { leftKey = true; btnLeft.classList.add("pressed"); };
    const handleLeftUp = () => { leftKey = false; btnLeft.classList.remove("pressed"); };
    const handleRightDown = () => { rightKey = true; btnRight.classList.add("pressed"); };
    const handleRightUp = () => { rightKey = false; btnRight.classList.remove("pressed"); };

    startBtn.addEventListener("click", startGame);
    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("keyup", handleKeyUp);

    btnLeft.addEventListener("pointerdown", handleLeftDown);
    btnLeft.addEventListener("pointerup", handleLeftUp);
    btnLeft.addEventListener("pointerleave", handleLeftUp);
    
    btnRight.addEventListener("pointerdown", handleRightDown);
    btnRight.addEventListener("pointerup", handleRightUp);
    btnRight.addEventListener("pointerleave", handleRightUp);

    // Initialization
    initRoad();
    drawRoad();
    drawRoadLines();
    drawCar(W / 2, H - 100, playerW, playerH, "#00f0ff", true);

    // --- CLEANUP ---
    return () => {
      cancelAnimationFrame(animId);
      startBtn.removeEventListener("click", startGame);
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("keyup", handleKeyUp);
      
      btnLeft.removeEventListener("pointerdown", handleLeftDown);
      btnLeft.removeEventListener("pointerup", handleLeftUp);
      btnLeft.removeEventListener("pointerleave", handleLeftUp);
      
      btnRight.removeEventListener("pointerdown", handleRightDown);
      btnRight.removeEventListener("pointerup", handleRightUp);
      btnRight.removeEventListener("pointerleave", handleRightUp);
    };
  }, []);

  return (
    <>
      <style dangerouslySetInnerHTML={{__html: `
        @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@700;900&family=Share+Tech+Mono&display=swap');
        
        #game-root {
          width: 100%; min-height: 520px;
          background: #0a0a0f;
          font-family: 'Share Tech Mono', monospace;
          display: flex; flex-direction: column; align-items: center;
          padding: 0; overflow: hidden; position: relative;
        }
        #hud {
          width: 100%; display: flex; justify-content: space-between; align-items: center;
          padding: 10px 20px; z-index: 20;
          background: rgba(10,10,15,0.9);
          border-bottom: 1px solid #1a1a2e;
        }
        .hud-item { display: flex; flex-direction: column; align-items: center; }
        .hud-label { font-size: 10px; color: #555; letter-spacing: 2px; text-transform: uppercase; }
        .hud-val { font-family: 'Orbitron', sans-serif; font-size: 18px; font-weight: 700; color: #00f0ff; }
        #game-area { width: 100%; max-width: 400px; position: relative; overflow: hidden; }
        #road-canvas { display: block; width: 100%; }
        #overlay {
          position: absolute; inset: 0; display: flex; flex-direction: column;
          align-items: center; justify-content: center; background: rgba(10,10,15,0.92);
          z-index: 30;
        }
        #overlay h1 {
          font-family: 'Orbitron', sans-serif; font-size: 32px; font-weight: 900;
          color: #00f0ff; letter-spacing: 4px; margin-bottom: 8px;
          text-shadow: 0 0 20px #00f0ff88;
        }
        #overlay .sub { font-size: 13px; color: #888; margin-bottom: 28px; letter-spacing: 2px; }
        #overlay .score-display { font-size: 22px; color: #ffd700; font-family: 'Orbitron', sans-serif; margin-bottom: 20px; }
        #start-btn {
          background: transparent; border: 1px solid #00f0ff; color: #00f0ff;
          font-family: 'Orbitron', sans-serif; font-size: 14px; letter-spacing: 3px;
          padding: 12px 36px; cursor: pointer; text-transform: uppercase;
          transition: all 0.2s;
        }
        #start-btn:hover { background: #00f0ff22; box-shadow: 0 0 16px #00f0ff44; }
        #controls {
          width: 100%; display: flex; justify-content: center; gap: 12px;
          padding: 10px; background: #0a0a0f; border-top: 1px solid #1a1a2e;
        }
        .ctrl-btn {
          background: #111120; border: 1px solid #2a2a4a; color: #aaa;
          font-family: 'Orbitron', sans-serif; font-size: 12px; padding: 10px 24px;
          cursor: pointer; border-radius: 4px; user-select: none;
          transition: all 0.1s; letter-spacing: 1px;
          -webkit-tap-highlight-color: transparent;
        }
        .ctrl-btn:active, .ctrl-btn.pressed { background: #00f0ff22; border-color: #00f0ff; color: #00f0ff; }
      `}} />

      <div id="game-root" ref={gameRef}>
        <div id="hud">
          <div className="hud-item">
            <span className="hud-label">Score</span>
            <span className="hud-val" id="score-hud">0</span>
          </div>
          <div className="hud-item">
            <span className="hud-label">Speed</span>
            <span className="hud-val" id="speed-hud">0</span>
          </div>
          <div className="hud-item">
            <span className="hud-label">Best</span>
            <span className="hud-val" id="best-hud">0</span>
          </div>
        </div>
        <div id="game-area">
          <canvas id="road-canvas"></canvas>
          <div id="overlay">
            <h1>NITRO RUSH</h1>
            <div className="sub">AVOID THE TRAFFIC · SURVIVE</div>
            <div className="score-display" id="overlay-score" style={{ display: "none" }}></div>
            <button id="start-btn">START ENGINE</button>
            <div style={{ marginTop: "16px", fontSize: "11px", color: "#555", letterSpacing: "1px" }}>
              ← → KEYS OR BUTTONS BELOW
            </div>
          </div>
        </div>
        <div id="controls">
          <button className="ctrl-btn" id="btn-left">◀ LEFT</button>
          <button className="ctrl-btn" id="btn-right">RIGHT ▶</button>
        </div>
      </div>
    </>
  );
}
