import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-white " lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased   overflow-x-hidden `}
      >
        <Navbar />
        <div className="max-w-screen-3xl mx-auto">
          {children}
        </div>
        <div className="bg-[#F7F8ED]">
          <Footer />
        </div>
      </body>
    </html>
  );
}
