// import { Caveat } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/layouts/Navbar";
// import Footer from "@/components/layouts/Footer";

// const caveat = Caveat({
//   variable: "--font-caveat",
//   subsets: ["latin"],
//   display: "swap",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html className="bg-white " lang="en">
//       <body
//         className={`${caveat.className} antialiased overflow-x-hidden`}
//       >
//         <Navbar />
//         <div className="max-w-screen-3xl mx-auto">
//           {children}
//         </div>
//         <div className="bg-[#F7F8ED]">
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }

"use client";

import React from "react";

export default function CarRacingGame() {
  return (
    <div
      style={{
        width: "100%",
        height: "100vh",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: "#000",
      }}
    >
      <h1
        style={{
          fontSize: "80px",
          color: "#fff",
          textAlign: "center",
          fontWeight: "bold",
          padding: "20px",
        }}
      >
        This Site Has Been Taken Down By Owner
      </h1>
    </div>
  );
}
