import { Caveat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-white " lang="en">
      <body
        className={`${caveat.className} antialiased overflow-x-hidden`}
      >
        <Navbar />
        <div className="max-w-screen-3xl mx-auto">
          {children}
        </div>
        <div className="bg-[#F7F8ED]">
          <Footer />
        </div>
      </body>
    </html>
  );
}
